Update pipeline chatelo-quality-pipeline

diff --git a/.harness/orgs/default/projects/chatelo/pipelines/chatelo_quality_pipeline.yaml b/.harness/orgs/default/projects/chatelo/pipelines/chatelo_quality_pipeline.yaml
--- a/.harness/orgs/default/projects/chatelo/pipelines/chatelo_quality_pipeline.yaml
+++ b/.harness/orgs/default/projects/chatelo/pipelines/chatelo_quality_pipeline.yaml
@@ -58,6 +58,15 @@ pipeline:
                       npm install oxlint
 
                       echo 'Installed Oxlint and Oxfmt'
+                      echo '#######################################################'
+                      echo 'Running oxlint'
+
+                      if npm run lint:ox; then
+                          echo 'Oxlint Check Has Passed'
+                      else
+                          echo 'Oxlint Failed!'
+                          exit 1
+                      fi
                     resources:
                       limits:
                         memory: 2Gi
